[package]
name = "bad_lock"
authors = ["lopo<lopo@zju.edu.cn>"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
cbc = { version = "0.1.2", features = ["alloc", "block-padding"] }
clap = "4.5.7"
md5 = "0.7.0"
wasm-bindgen = "0.2.92"