[package]
name = "image_lock"
authors = ["lopo<lopo@zju.edu.cn>"]
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
cbc = { version = "0.1.2", features = ["alloc", "block-padding"] }
md5 = "0.7.0"